services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8898:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: {{ pg_admin }}
      PGADMIN_DEFAULT_PASSWORD: {{ pg_pw }}
    volumes:
      - "./pgadmin-data:/var/lib/pgadmin"
